export const ACTIONS = {
  LOGIN_START: 'LOGIN_START',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILED: 'LOGIN_FAILED',

  LOGOUT: 'LOGOUT',

  YOUTUBE_FEED_SUCCESS: 'YOUTUBE_FEED_SUCCESS',
  YOUTUBE_FEED_FAILED: 'YOUTUBE_FEED_FAILED',
  YOUTUBE_FEED_START: 'YOUTUBE_FEED_START',
  YOUTUBE_FEED_CLEAR: 'YOUTUBE_FEED_CLEAR',

  SELECTED_VIDEO_SUCCESS: 'SELECTED_VIDEO_SUCCESS',
  SELECTED_VIDEO_FAILED: 'SELECTED_VIDEO_FAILED',
  SELECTED_VIDEO_START: 'SELECTED_VIDEO_START',
  SELECTED_VIDEO_CLEAR: 'SELECTED_VIDEO_CLEAR',

  SELECTED_CHANNEL_SUCCESS: 'SELECTED_CHANNEL_SUCCESS',
  SELECTED_CHANNEL_FAILED: 'SELECTED_CHANNEL_FAILED',
  SELECTED_CHANNEL_START: 'SELECTED_CHANNEL_START',
  SELECTED_CHANNEL_CLEAR: 'SELECTED_CHANNEL_CLEAR',

  VIDEO_COMMENTS_SUCCESS: 'VIDEO_COMMENTS_SUCCESS',
  VIDEO_COMMENTS_FAILED: 'VIDEO_COMMENTS_FAILED',
  VIDEO_COMMENTS_START: 'VIDEO_COMMENTS_START',
  VIDEO_COMMENTS_CLEAR: 'VIDEO_COMMENTS_CLEAR',

  RELATED_VIDEOS_SUCCESS: 'RELATED_VIDEOS_SUCCESS',
  RELATED_VIDEOS_FAILED: 'RELATED_VIDEOS_FAILED',
  RELATED_VIDEOS_START: 'RELATED_VIDEOS_START',
  RELATED_VIDEOS_CLEAR: 'RELATED_VIDEOS_CLEAR',

  SEARCH_VIDEOS_START: 'SEARCH_VIDEOS_START',
  SEARCH_VIDEOS_FAILED: 'SEARCH_VIDEOS_FAILED',
  SEARCH_VIDEOS_SUCCESS: 'SEARCH_VIDEOS_SUCCESS',
  SEARCH_VIDEOS_CLEAR: 'SEARCH_VIDEOS_CLEAR',

  SUBSCRIPTIONS_CHANNEL_REQUEST: 'SUBSCRIPTIONS_CHANNEL_REQUEST',
  SUBSCRIPTIONS_CHANNEL_SUCCESS: 'SUBSCRIPTIONS_CHANNEL_SUCCESS',
  SUBSCRIPTIONS_CHANNEL_FAIL: 'SUBSCRIPTIONS_CHANNEL_FAIL',

  CHANNEL_VIDEOS_REQUEST: 'CHANNEL_VIDEOS_REQUEST',
  CHANNEL_VIDEOS_SUCCESS: 'CHANNEL_VIDEOS_SUCCESS',
  CHANNEL_DETAILS_FAIL: 'CHANNEL_DETAILS_FAIL',
};
